volumes:
  postgres:
  redis:
  minio:
services:
  main:
    depends_on:
      - postgres
      - redis
      - minio
      - mailhog
    build: .
    environment:
      POSTGRES_HOST: postgres:5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nextcloud
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: admin
      REDIS_HOST: redis
      OBJECTSTORE_S3_KEY: minioadmin
      OBJECTSTORE_S3_SECRET: minioadmin
      OBJECTSTORE_S3_BUCKET: nextcloud
      OBJECTSTORE_S3_REGION: void
      OBJECTSTORE_S3_HOST: minio
      OBJECTSTORE_S3_PORT: 9000
      SMTP_HOST: mailhog
      MAIL_FROM_ADDRESS: nextcloud@example.com
    ports:
      - 80:80
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nextcloud
    volumes:
      - postgres:/var/lib/postgresql/data:delegated
  redis:
    image: redis:alpine
    volumes:
      - redis:/data:delegated
  minio:
    image: minio/minio
    volumes:
      - minio:/data:delegated
    command:
      - server
      - /data
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
